### ISSUE TITLE
Cannot seed data onlinux

### ISSUE THREAD

**Issue by tarikrital** [commercelayer/commercelayer-cli-plugin-seeder#115]
### Describe the bug

I cloned the [repo](https://github.com/commercelayer/demo-store) but when I tried to seed data it doesn't work!

```
commercelayerdemo$ npm run seeder:seed -ws --if-present

> @commercelayer/demo-store-setup@2.2.0 seeder:seed
> npx ts-node ./scripts/seed.ts

Need to install the following packages:
  ts-node@10.9.2
Ok to proceed? (y) y
Error: Command failed: commercelayer applications:info --json
 ›   Error: Unable to find configuration file for application

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at getCurrentApplicationInfo (/demo-store-core/packages/setup/scripts/utils/application.ts:17:35)                                                                           
    at commercelayerdemo/demo-store-core/packages/setup/scripts/seed.ts:12:59
    at Generator.next (<anonymous>)
    at commercelayerdemo/demo-store-core/packages/setup/scripts/seed.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (commercelayerdemo/demo-store-core/packages/setup/scripts/seed.ts:4:12)                                                                                                         
    at commercelayerdemo/demo-store-core/packages/setup/scripts/seed.ts:10:13 {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(64) [Uint8Array] [
       32, 226, 128, 186,  32,  32,  32,  69, 114, 114, 111,
      114,  58,  32,  85, 110,  97,  98, 108, 101,  32, 116,
      111,  32, 102, 105, 110, 100,  32,  99, 111, 110, 102,
      105, 103, 117, 114,  97, 116, 105, 111, 110,  32, 102,
      105, 108, 101,  32, 102, 111, 114,  32,  97, 112, 112,
      108, 105,  99,  97, 116, 105, 111, 110,  10
    ]
  ],
  pid: 473689,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(64) [Uint8Array] [
     32, 226, 128, 186,  32,  32,  32,  69, 114, 114, 111,
    114,  58,  32,  85, 110,  97,  98, 108, 101,  32, 116,
    111,  32, 102, 105, 110, 100,  32,  99, 111, 110, 102,
    105, 103, 117, 114,  97, 116, 105, 111, 110,  32, 102,
    105, 108, 101,  32, 102, 111, 114,  32,  97, 112, 112,
    108, 105,  99,  97, 116, 105, 111, 110,  10
  ]
}
npm ERR! Lifecycle script `seeder:seed` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @commercelayer/demo-store-setup@2.2.0 
npm ERR!   at location: commercelayerdemo/demo-store-core/packages/setup          
```         

### System

Linux

**Comment by marcomontalbano** [comment]
Hi @wpplumber, the error message you get `Unable to find configuration file for application` is thrown when the application is not properly configured.

You can read "[setting up your organization](https://github.com/commercelayer/demo-store?tab=readme-ov-file#setting-up-your-organization)" to configure the application.

As mentioned there, you should run this command:

```sh
commercelayer applications:login \
  --clientId Oy5F2TbPYhOZsxy1tQd9ZVZ... \
  --clientSecret 1ZHNJUgn_1lh1mel06gGDqa... \
  --organization my-awesome-organization \
  --alias cli-admin
```

After that you can double-check if the application is properly configured by running:

```sh
commercelayer applications:info
```

Let us know if you've further questions.

**Comment by tarikrital** [comment]
I was able to run it.

Thank you.
